version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    registries:
      - npm-tradeshift
registries:
  npm-tradeshift:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_READ_TOKEN}}
