version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    registries:
      - npm-tradeshift
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-minor, version-update:semver-patch]
registries:
  npm-tradeshift:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_READ_TOKEN}}
