module.exports = {
	plugins: ['jest'],
	rules: {
		'jest/no-disabled-tests': 'warn',
		'jest/no-focused-tests': 'error',
		'jest/no-identical-title': 'error',
		'jest/valid-expect': 'error',
		'jest/no-alias-methods': 'off',
		'jest/no-large-snapshots': ['warn', { maxSize: 300 }],
		'jest/no-test-prefixes': 'error',
		'jest/prefer-to-contain': 'warn',
		'jest/prefer-to-have-length': 'warn',
		'jest/valid-describe-callback': 'error',
		'jest/valid-expect-in-promise': 'error',
		'jest/consistent-test-it': 'off',
		'jest/prefer-lowercase-title': 'off',
		'jest/no-hooks': 'off',
		'jest/no-jasmine-globals': 'off',
		'jest/no-done-callback': 'off',
		'jest/prefer-expect-assertions': 'off',
		'jest/prefer-equality-matcher': 'off',
		'jest/expect-expect': 'off',
		'jest/no-test-return-statement': 'off',
		'jest/prefer-strict-equal': 'off',
		'jest/prefer-to-be': 'warn',
		'jest/prefer-spy-on': 'off',
		'jest/prefer-todo': 'warn',
		'jest/prefer-called-with': 'error',
		'jest/valid-title': 'error',
		'jest/no-mocks-import': 'error',
		'jest/no-commented-out-tests': 'warn',
		'jest/no-duplicate-hooks': 'off',
		'jest/no-export': 'error',
		'jest/no-standalone-expect': 'off',
		'jest/no-conditional-expect': 'error',
		'jest/require-top-level-describe': 'off',
		'jest/prefer-hooks-on-top': 'error'
	},
	env: {
		'jest/globals': true
	}
};
